### ISSUE TITLE
Make the sidebar responsive on mobile

### ISSUE THREAD

**Issue by Oslonline** [Oslonline/oslo-toolbox#1]
Make the sidebar reponsive for mobile viewing.

- Make sure to use existing components when possible.
- Make sure to use global project styling (colors, border....).
- The sidebar needs to be collapsible.

Feel free to ask to be assigned to this. 
Be sure your gonna work on it and you have the needed experience ;)

**Comment by s-babaeizadeh** [comment]
I am interested in taking on this issue. Please assign it to me.

**Comment by Oslonline** [comment]
Hi again ! Sorry for the delay in response I am on vacation. Of course I'll assign you right away, good luck implementing this feature.
